name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1 12 * * 1-5' #M-F at 12:01pm UTC

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch sg levels data
      run: |-
        today=$(date +"%m-%d-%Y")
        curl https://spotgamma-system-files.s3.amazonaws.com/SPXstr31.csv > ./data/SPX-${today}.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
