name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1 12,16 * * 1-5' #M-F at 12:01pm UTC, ~5:01am/9:01am PST
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch sg levels data
      run: |
        today=$(date +"%m-%d-%Y")
        curl https://spotgamma-system-files.s3.amazonaws.com/SPXstr31.csv > ./data/SPX-${today}.csv
        git commit -m 'Latest data'
